// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nkboddifbnuheqzdxhas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rYm9kZGlmYm51aGVxemR4aGFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMDk3MjAsImV4cCI6MjA3MzU4NTcyMH0.nd15i1IUyPmsSTFeDcC9WFjokoaujohtFfzcu28nJ2c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});